import React, { useState } from "react"
import '../styles/styles.css'
import Character from '../types/Character';
import WordList from "../components/WordList";
import HomeStats from "../components/HomeStats";
import { db } from "../utils/Firebase";
import { collection, getDocs, query, where, limit, or } from "firebase/firestore";
import { addToStore, getAllItemsFromStore} from "../indexed_db/character";


interface DictionaryProps {
    title: string;
}

// this list was generated by chatGPT with the following prompt: 
/* give me a list of 20 JLPT N5 kanji formatted as a list of typescript type Character. the Character type is defined as such: type Character = {
    id: number;
    unicode: string;
    hiragana: string;
    english: string;
};, where unicode is the kanji*/
const jlptN5Kanji: Character[] = [
  { id: 1, unicode: '一', hiragana: 'いち', english: 'one' },
  { id: 2, unicode: '二', hiragana: 'に', english: 'two' },
  { id: 3, unicode: '三', hiragana: 'さん', english: 'three' },
  { id: 4, unicode: '四', hiragana: 'し/よん', english: 'four' },
  { id: 5, unicode: '五', hiragana: 'ご', english: 'five' },
  { id: 6, unicode: '六', hiragana: 'ろく', english: 'six' },
  { id: 7, unicode: '七', hiragana: 'しち/なな', english: 'seven' },
  { id: 8, unicode: '八', hiragana: 'はち', english: 'eight' },
  { id: 9, unicode: '九', hiragana: 'きゅう/く', english: 'nine' },
  { id: 10, unicode: '十', hiragana: 'じゅう', english: 'ten' },
  { id: 11, unicode: '百', hiragana: 'ひゃく', english: 'hundred' },
  { id: 12, unicode: '千', hiragana: 'せん', english: 'thousand' },
  { id: 13, unicode: '円', hiragana: 'えん', english: 'yen' },
  { id: 14, unicode: '日', hiragana: 'にち/ひ', english: 'day/sun' },
  { id: 15, unicode: '月', hiragana: 'げつ/がつ', english: 'month/moon' },
  { id: 16, unicode: '火', hiragana: 'か', english: 'fire' },
  { id: 17, unicode: '水', hiragana: 'すい', english: 'water' },
  { id: 18, unicode: '木', hiragana: 'もく', english: 'tree' },
  { id: 19, unicode: '金', hiragana: 'きん/こん', english: 'gold/metal' },
  { id: 20, unicode: '土', hiragana: 'ど/と', english: 'earth' },
];

const DictionaryView : React.FC<DictionaryProps> = ({title}) => {
  const [characters,setCharacters] = useState<Character[]>(jlptN5Kanji)

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
      const formData = new FormData(event.currentTarget);
      const text = formData.get("text") as string;
      console.log(text);

      search(text);
      
  }
  const search = async (text:string ) => {
    const characterRef = await collection(db,"Character");

    // const q = query(characterRef, where('meanings', 'array-contains', text));
    // const q = query(characterRef,
    //   or(or(where('meanings', 'array-contains', text),where('literal','==',text)),or(where('readings.value', '>=', text)
    //   ,where('readings.value', '<=', text+ '\uf8ff'))),limit(10));

    //TODO add support for readings search?
    // const q = query(characterRef,
    //   or(where('meanings','array-contains',text),where('literal','==',text)),limit(10));

    const q = query(characterRef,limit(10));

    const querySnapshot = await getDocs(q);
    const convertedCharacters:Character[] = []

    querySnapshot.forEach((doc:any) => {
      //TODO Replace with unified type
      console.log(doc.id, " => ", doc.data());
      convertedCharacters.push({
        id: doc.id,
        unicode: doc.data()['literal'],
        hiragana:doc.data()['readings'].map((reading:any) => {if(reading.type === 'ja_kun') {
          return reading.value
        }}).join(''),
        english:doc.data()['meanings'].join('/')
      })
      

    });
    setCharacters(convertedCharacters);
    addToStore('Character',convertedCharacters).then(() => {
      getAllItemsFromStore('Character').then((result: any) => {
        console.log(result)
      })
    });


  }
  return (
    <div className="dictionary-view">

      <p  className="my-words">My Words</p>
      <form onSubmit={handleSubmit} id='search-form'>
      <input name="text" type="text" className="search-bar" />
      <button type="submit">Search</button>
      </form>
      <HomeStats />
      <WordList words={characters}/>
      
    </div>
  )
}

export default DictionaryView;